# Example compose file
#
# Change the VARS-GO-HERE values below.
#
# Usage: docker stack deploy -c minio-swarm.yaml minio
#
version: '3.2'

services:
 minio1:
  image: noahgray/minio-wormhole
  deploy:
    mode: global
  volumes:
   - type: bind
     source: /mnt/block-storage/var/lib/minio
     target: /export
  ports:
   - "9001:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: VARS-GO-HERE
   MINIO_SECRET_KEY: VARS-GO-HERE
   FLY_TOKEN: VARS-GO-HERE
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: wormhole minio server http://minio1/export http://minio2/export http://minio3/export http://minio4/export

 minio2:
  image: noahgray/minio-wormhole
  deploy:
    mode: global
  volumes:
   - type: bind
     source: /mnt/block-storage/var/lib/minio
     target: /export
  ports:
   - "9002:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: VARS-GO-HERE
   MINIO_SECRET_KEY: VARS-GO-HERE
   FLY_TOKEN: VARS-GO-HERE
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: wormhole minio server http://minio1/export http://minio2/export http://minio3/export http://minio4/export

 minio3:
  image: noahgray/minio-wormhole
  deploy:
    mode: global
  volumes:
    - type: bind
      source: /mnt/block-storage/var/lib/minio
      target: /export
  ports:
   - "9003:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: VARS-GO-HERE
   MINIO_SECRET_KEY: VARS-GO-HERE
   FLY_TOKEN: VARS-GO-HERE
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: wormhole minio server http://minio1/export http://minio2/export http://minio3/export http://minio4/export

 minio4:
  image: noahgray/minio-wormhole
  deploy:
    mode: global
  volumes:
   - type: bind
     source: /mnt/block-storage/var/lib/minio
     target: /export
  ports:
   - "9004:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: VARS-GO-HERE
   MINIO_SECRET_KEY: VARS-GO-HERE
   FLY_TOKEN: VARS-GO-HERE
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: wormhole minio server http://minio1/export http://minio2/export http://minio3/export http://minio4/export

networks:
 minio_distributed:
  driver: overlay